config/routes.rb
Volta::Application.routes.draw do
  root to: 'welcome#index'

  resources :products do
    resources :comments, controller: 'product_comments', only: [:create]
  end

  resources :events do
    get :fav, on: :collection
    resources :comments, controller: 'event_comments', only: [:create]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :description, presence: true
  has_many :comments, as: :commentable
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose(:comment, attributes: :comment_attributes)
  expose(:comments)
  expose(:event) { Event.find(params[:event_id]) }
  expose(:product) { Product.find(params[:product_id]) }

  def index; end
  def new; end
  def show; end
  def edit; end

  def create
    if params[:product_id].present?
      comment.commentable = product
    else
      comment.commentable = event
    end

    if comment.save
      flash[:success] = "V'oila!"
      redirect_to root_path
    else
      flash[:error] = 'Nie poszło nam...'
      render :new
    end
  end

  def update
    if comment.update(comment_attributes)
      flash[:success] = "V'oila!"
      redirect_to root_path
    else
      flash[:error] = 'Nie poszło nam...'
      render :edit
    end
  end

  def destroy
    if comment.destroy
      flash[:success] = "V'oila!"
      redirect_to root_path
    else
      flash[:success] = "Nie poszło nam.."
      redirect_to root_path
    end
  end

  private

  def save_commentable(element)
    if element.save
      flash[:success] = "V'oila!"
      redirect_to root_path
    else
      flash[:error] = 'Nie poszło nam...'
      render :new
    end
  end

  def comment_attributes
    params.require(:comment).permit(:content, :event_id)
  end
end

app/controllers/event_comments_controller.rb
class EventCommentsController < CommentsController
  expose(:event) { Event.find(params[:event_id]) }

  def create
    comment.commentable = event
    save_commentable(comment)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  expose(:event, attributes: :event_attributes)
  expose(:events)

  def index
  end

  def new
  end

  def fav; end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def create
    if event.save
      flash[:success] = "V'oila!"
      redirect_to events_path
    else
      flash[:error] = 'Nie poszło nam...'
      render :new
    end
  end

  def update
    if event.update(event_attributes)
      flash[:success] = "V'oila!"
      redirect_to events_path
    else
      flash[:error] = 'Nie poszło nam...'
      render :edit
    end
  end

  def destroy
    if event.destroy
      flash[:success] = "V'oila!"
      redirect_to events_path
    else
      flash[:success] = "Nie poszło nam.."
      redirect_to events_path
    end
  end

  private

  def event_attributes
    params.require(:event).permit(:name, :description)
  end
end

app/controllers/product_comments_controller.rb
class ProductCommentsController < CommentsController
  expose(:product) { Product.find(params[:product_id]) }

  def create
    comment.commentable = product
    save_commentable(comment)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  expose(:product, attributes: :product_attributes)
  expose(:products)

  def index
  end

  def new
  end

  def fav; end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    if product.update(product_attributes)
      flash[:success] = "V'oila!"
      redirect_to products_path
    else
      flash[:error] = 'Nie poszło nam...'
      render :edit
    end
  end

  def destroy
    if product.destroy
      flash[:success] = "V'oila!"
      redirect_to products_path
    else
      flash[:success] = "Nie poszło nam.."
      redirect_to products_path
    end
  end

  private

  def product_attributes
    params.require(:product).permit(:name, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/events_helper.rb
module EventsHelper
  def pretty_date(date)
    date.strftime("%m/%d/%Y")
  end
end

app/views/comments/_comment.html.erb
<p>
  <%= comment.content %>
  <%= link_to 'Edit comment', edit_comment_path(id: comment.id) %>
  <%= link_to 'Show comment', comment_path(id: comment.id) %>
  <%= link_to 'Delete comment', comment_path(id: comment.id), method: :delete %>
</p>

app/views/comments/edit.html.erb
<%= flash[:error] %>
<%= form_for comment do |form_field| %>
  <%= form_field.label :content %>
  <%= form_field.text_field :content %>

  <%= form_field.label :event_id %>
  <%= form_field.select :event_id, options_for_select(Event.all.map { |x| [x.name, x.id] }) %>

  <%= form_field.submit 'Add new comment' %>

<% end %>

<%= render 'greetings' %>

app/views/comments/index.html.erb
<%= link_to 'Add new comment', new_comment_path %>

<br />
<%= flash[:success] %>
<br />

<%= render comments %>

<%= render 'greetings' %>

app/views/comments/new.html.erb
<%= flash[:error] %>
<%= form_for comment do |form_field| %>
  <%= form_field.label :content %>
  <%= form_field.text_field :content %>

  <%= form_field.label :event_id %>
  <%= form_field.select :event_id, options_for_select(Event.all.map { |x| [x.name, x.id] }) %>

  <%= form_field.submit 'Add new comment' %>

<% end %>

<%= render 'greetings' %>

app/views/comments/show.html.erb
<p>
  <%= comment.content %>
</p>
<p>
  <strong>EVENT NAME:</strong>
  <%= comment.event.name %>
</p>

app/views/events/_event.html.erb
<p>
  <%= event.name %>
  <%= link_to 'Edit event', edit_event_path(id: event.id) %>
  <%= link_to 'Show event', event_path(id: event.id) %>
  <%= link_to 'Delete event', event_path(id: event.id), method: :delete %>
</p>

app/views/events/edit.html.erb
<%= flash[:error] %>
<%= form_for event do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :description %>
  <%= form.text_area :description %>
  <%= form.submit 'Edit event' %>
<% end %>

<%= render 'greetings' %>

app/views/events/index.html.erb
<%= link_to 'Add new event', new_event_path %>

<br />
<%= flash[:success] %>
<br />

<%= render events %>

<%= render 'greetings' %>

app/views/events/new.html.erb
<%= flash[:error] %>
<%= form_for event do |form_field| %>
  <%= form_field.label :name %>
  <%= form_field.text_field :name %>
  <%= form_field.label :description %>
  <%= form_field.text_area :description %>

  <%= form_field.submit 'Add new event' %>

<% end %>

<%= render 'greetings' %>

app/views/events/show.html.erb
<p>
  <%= event.name %>
</p>
<p>
  <%= event.description %>
  <%= pretty_date(event.created_at) %>
</p>
<p>
  <strong>KOMENTARZE:</strong>
  <% event.comments.each do |comment| %>
    <%= comment.content %>
  <% end %>
</p>
<p>
  <strong>NOWY KOMENTARZ:</strong>
  <%= form_for @comment, url: event_comments_path(event_id: event.id) do |form| %>
    <%= form.text_field :content %>
    <%= form.submit %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Volta</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class="col-md-4">MENU</div>
      <div class="col-md-8"><%= yield %></div>
    </div>
  </div>
</body>
</html>

app/views/products/_greetings.html.erb
Pozdrowienia dla Blazeja

app/views/products/_product.html.erb
<p>
  <%= product.name %>
  <%= link_to 'Edit product', edit_product_path(id: product.id) %>
  <%= link_to 'Show product', product_path(id: product.id) %>
  <%= link_to 'Delete product', product_path(id: product.id), method: :delete %>
</p>

app/views/products/edit.html.erb
<%= flash[:error] %>
<%= form_for product do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :description %>
  <%= form.text_area :description %>
  <%= form.submit 'Edit product' %>
<% end %>

<%= render 'greetings' %>

app/views/products/fav.html.erb
fav..

app/views/products/index.html.erb
<%= link_to 'Add new product', new_product_path %>

<br />
<%= flash[:success] %>
<br />

<%= render products %>

<%= render 'greetings' %>

app/views/products/new.html.erb
<%= flash[:error] %>
<%= form_for product do |form_field| %>
  <%= form_field.label :name %>
  <%= form_field.text_field :name %>
  <%= form_field.label :description %>
  <%= form_field.text_area :description %>

  <%= form_field.submit 'Add new product' %>

<% end %>

<%= render 'greetings' %>

app/views/products/show.html.erb
<p>
  <%= product.name %>
</p>
<p>
  <%= product.name %>
  <%= product.description %>
  <%= pretty_date(product.created_at) %>
</p>
<p>
  <strong>KOMENTARZE:</strong>
  <% product.comments.each do |comment| %>
    <%= comment.content %>
  <% end %>
</p>
<p>
  <strong>NOWY KOMENTARZ:</strong>
  <%= form_for @comment, url: product_comments_path(product_id: product.id) do |form| %>
    <%= form.text_field :content %>
    <%= form.submit %>
  <% end %>
</p>

app/views/welcome/index.html.erb
<%= link_to 'New product', products_path, class: 'btn btn-default ' %>
<%= link_to 'New event', events_path, class: 'btn btn-default ' %>

<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>

<button class='btn btn-default' id='js-load-state'>Loading State</button>